# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: '9.4.1'
    postgresql:
      repo: puppetlabs/postgresql
      ref: '10.0.2'
    # Needed by Postgresql module
    apt:
      repo: puppetlabs/apt
      ref: '9.1.0'
    python:
      repo: puppet/python
      ref: '7.0.0'
    # Needed by Python module
    epel:
      repo: puppet/epel
      ref: '5.0.0'
    systemd:
      repo: puppet/systemd
      ref: '6.1.0'
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      ref: '2.0.0'
  symlinks:
    patroni: "#{source_dir}"
