.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el8
      - el9
      - debian-11
      - ubuntu-2004
      - ubuntu-2204
    puppet:
      - puppet7
      - puppet8
.travis.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: coveralls
Rakefile:
  changelog_user: tailored-automation
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
spec/acceptance/nodesets/el8.yml:
  unmanaged: true
spec/acceptance/nodesets/el9.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-11.yml:
  unmanaged: true
